graph [
comment "Automatically generated by Graphing tool"
directed  1
id  1
label "Phylogeny Tree....
"node [
id 1
label "s179"
defaultAtrribute   1
]
node [
id 2
label "s141"
defaultAtrribute   1
]
node [
id 3
label "s130"
defaultAtrribute   1
]
node [
id 4
label "s129"
defaultAtrribute   1
]
node [
id 5
label "s108"
defaultAtrribute   1
]
node [
id 6
label "s105"
defaultAtrribute   1
]
node [
id 7
label "s69"
defaultAtrribute   1
]
node [
id 8
label "s23"
defaultAtrribute   1
]
node [
id 10
label "s192"
defaultAtrribute   1
]
node [
id 11
label "s181"
defaultAtrribute   1
]
node [
id 19
label "s138"
defaultAtrribute   1
]
node [
id 20
label "s113"
defaultAtrribute   1
]
node [
id 65
label "s109"
defaultAtrribute   1
]
node [
id 66
label "s98"
defaultAtrribute   1
]
node [
id 67
label "s57"
defaultAtrribute   1
]
node [
id 68
label "s56"
defaultAtrribute   1
]
node [
id 69
label "s49"
defaultAtrribute   1
]
node [
id 70
label "s19"
defaultAtrribute   1
]
node [
id 72
label "s184"
defaultAtrribute   1
]
node [
id 73
label "s173"
defaultAtrribute   1
]
node [
id 113
label "s123"
defaultAtrribute   1
]
node [
id 119
label "s140"
defaultAtrribute   1
]
node [
id 114
label "s41"
defaultAtrribute   1
]
node [
id 120
label "s131"
defaultAtrribute   1
]
node [
id 121
label "s136"
defaultAtrribute   1
]
node [
id 116
label "s178"
defaultAtrribute   1
]
node [
id 115
label "s183"
defaultAtrribute   1
]
node [
id 117
label "s160"
defaultAtrribute   1
]
node [
id 118
label "s61"
defaultAtrribute   1
]
node [
id 123
label "s12"
defaultAtrribute   1
]
node [
id 103
label "s132"
defaultAtrribute   1
]
node [
id 108
label "s164"
defaultAtrribute   1
]
node [
id 122
label "s122"
defaultAtrribute   1
]
node [
id 106
label "s168"
defaultAtrribute   1
]
node [
id 107
label "s82"
defaultAtrribute   1
]
node [
id 109
label "s16"
defaultAtrribute   1
]
node [
id 104
label "s97"
defaultAtrribute   1
]
node [
id 110
label "s125"
defaultAtrribute   1
]
node [
id 111
label "s80"
defaultAtrribute   1
]
node [
id 105
label "s63"
defaultAtrribute   1
]
node [
id 87
label "s15"
defaultAtrribute   1
]
node [
id 102
label "s133"
defaultAtrribute   1
]
node [
id 112
label "s124"
defaultAtrribute   1
]
node [
id 124
label "s107"
defaultAtrribute   1
]
node [
id 125
label "s42"
defaultAtrribute   1
]
node [
id 126
label "s186"
defaultAtrribute   1
]
node [
id 89
label "s149"
defaultAtrribute   1
]
node [
id 90
label "s75"
defaultAtrribute   1
]
node [
id 91
label "s66"
defaultAtrribute   1
]
node [
id 92
label "s39"
defaultAtrribute   1
]
node [
id 93
label "s27"
defaultAtrribute   1
]
node [
id 94
label "s24"
defaultAtrribute   1
]
node [
id 95
label "s7"
defaultAtrribute   1
]
node [
id 96
label "s90"
defaultAtrribute   1
]
node [
id 100
label "s135"
defaultAtrribute   1
]
node [
id 97
label "s175"
defaultAtrribute   1
]
node [
id 88
label "s161"
defaultAtrribute   1
]
node [
id 98
label "s142"
defaultAtrribute   1
]
node [
id 99
label "s67"
defaultAtrribute   1
]
node [
id 101
label "s134"
defaultAtrribute   1
]
node [
id 74
label "s191"
defaultAtrribute   1
]
node [
id 75
label "s171"
defaultAtrribute   1
]
node [
id 76
label "s96"
defaultAtrribute   1
]
node [
id 77
label "s92"
defaultAtrribute   1
]
node [
id 78
label "s84"
defaultAtrribute   1
]
node [
id 79
label "s29"
defaultAtrribute   1
]
node [
id 80
label "s3"
defaultAtrribute   1
]
node [
id 85
label "s156"
defaultAtrribute   1
]
node [
id 81
label "s193"
defaultAtrribute   1
]
node [
id 71
label "s37"
defaultAtrribute   1
]
node [
id 86
label "s150"
defaultAtrribute   1
]
node [
id 149
label "s102"
defaultAtrribute   1
]
node [
id 150
label "s55"
defaultAtrribute   1
]
node [
id 151
label "s35"
defaultAtrribute   1
]
node [
id 152
label "s14"
defaultAtrribute   1
]
node [
id 82
label "s157"
defaultAtrribute   1
]
node [
id 83
label "s51"
defaultAtrribute   1
]
node [
id 84
label "s36"
defaultAtrribute   1
]
node [
id 9
label "s194"
defaultAtrribute   1
]
node [
id 12
label "s172"
defaultAtrribute   1
]
node [
id 13
label "s169"
defaultAtrribute   1
]
node [
id 14
label "s166"
defaultAtrribute   1
]
node [
id 15
label "s153"
defaultAtrribute   1
]
node [
id 16
label "s88"
defaultAtrribute   1
]
node [
id 17
label "s85"
defaultAtrribute   1
]
node [
id 18
label "s17"
defaultAtrribute   1
]
node [
id 21
label "s11"
defaultAtrribute   1
]
node [
id 24
label "s40"
defaultAtrribute   1
]
node [
id 35
label "s155"
defaultAtrribute   1
]
node [
id 36
label "s78"
defaultAtrribute   1
]
node [
id 37
label "s71"
defaultAtrribute   1
]
node [
id 38
label "s65"
defaultAtrribute   1
]
node [
id 39
label "s64"
defaultAtrribute   1
]
node [
id 40
label "s38"
defaultAtrribute   1
]
node [
id 41
label "s147"
defaultAtrribute   1
]
node [
id 42
label "s33"
defaultAtrribute   1
]
node [
id 43
label "s8"
defaultAtrribute   1
]
node [
id 52
label "s128"
defaultAtrribute   1
]
node [
id 50
label "s143"
defaultAtrribute   1
]
node [
id 51
label "s68"
defaultAtrribute   1
]
node [
id 47
label "s148"
defaultAtrribute   1
]
node [
id 48
label "s62"
defaultAtrribute   1
]
node [
id 44
label "s180"
defaultAtrribute   1
]
node [
id 45
label "s5"
defaultAtrribute   1
]
node [
id 46
label "s158"
defaultAtrribute   1
]
node [
id 26
label "s176"
defaultAtrribute   1
]
node [
id 27
label "s174"
defaultAtrribute   1
]
node [
id 49
label "s146"
defaultAtrribute   1
]
node [
id 53
label "s117"
defaultAtrribute   1
]
node [
id 54
label "s115"
defaultAtrribute   1
]
node [
id 55
label "s94"
defaultAtrribute   1
]
node [
id 56
label "s91"
defaultAtrribute   1
]
node [
id 57
label "s54"
defaultAtrribute   1
]
node [
id 61
label "s165"
defaultAtrribute   1
]
node [
id 60
label "s22"
defaultAtrribute   1
]
node [
id 58
label "s79"
defaultAtrribute   1
]
node [
id 59
label "s34"
defaultAtrribute   1
]
node [
id 22
label "s58"
defaultAtrribute   1
]
node [
id 127
label "s106"
defaultAtrribute   1
]
node [
id 130
label "s154"
defaultAtrribute   1
]
node [
id 131
label "s118"
defaultAtrribute   1
]
node [
id 132
label "s76"
defaultAtrribute   1
]
node [
id 133
label "s2"
defaultAtrribute   1
]
node [
id 135
label "s45"
defaultAtrribute   1
]
node [
id 145
label "s111"
defaultAtrribute   1
]
node [
id 146
label "s25"
defaultAtrribute   1
]
node [
id 140
label "s167"
defaultAtrribute   1
]
node [
id 141
label "s144"
defaultAtrribute   1
]
node [
id 143
label "s126"
defaultAtrribute   1
]
node [
id 142
label "s46"
defaultAtrribute   1
]
node [
id 136
label "s83"
defaultAtrribute   1
]
node [
id 134
label "s93"
defaultAtrribute   1
]
node [
id 137
label "s43"
defaultAtrribute   1
]
node [
id 138
label "s6"
defaultAtrribute   1
]
node [
id 153
label "s101"
defaultAtrribute   1
]
node [
id 144
label "s120"
defaultAtrribute   1
]
node [
id 139
label "s87"
defaultAtrribute   1
]
node [
id 128
label "s59"
defaultAtrribute   1
]
node [
id 129
label "s26"
defaultAtrribute   1
]
node [
id 147
label "s104"
defaultAtrribute   1
]
node [
id 148
label "s145"
defaultAtrribute   1
]
node [
id 23
label "s50"
defaultAtrribute   1
]
node [
id 62
label "s110"
defaultAtrribute   1
]
node [
id 63
label "s74"
defaultAtrribute   1
]
node [
id 64
label "s70"
defaultAtrribute   1
]
node [
id 154
label "s10"
defaultAtrribute   1
]
node [
id 164
label "s100"
defaultAtrribute   1
]
node [
id 157
label "s48"
defaultAtrribute   1
]
node [
id 158
label "s21"
defaultAtrribute   1
]
node [
id 159
label "s18"
defaultAtrribute   1
]
node [
id 161
label "s185"
defaultAtrribute   1
]
node [
id 162
label "s119"
defaultAtrribute   1
]
node [
id 163
label "s60"
defaultAtrribute   1
]
node [
id 160
label "s188"
defaultAtrribute   1
]
node [
id 155
label "s95"
defaultAtrribute   1
]
node [
id 156
label "s73"
defaultAtrribute   1
]
node [
id 28
label "s170"
defaultAtrribute   1
]
node [
id 29
label "s86"
defaultAtrribute   1
]
node [
id 30
label "s4"
defaultAtrribute   1
]
node [
id 25
label "s195"
defaultAtrribute   1
]
node [
id 31
label "s162"
defaultAtrribute   1
]
node [
id 32
label "s159"
defaultAtrribute   1
]
node [
id 33
label "s89"
defaultAtrribute   1
]
node [
id 34
label "s9"
defaultAtrribute   1
]
edge [
source 1
target  2
label ""
]
edge [
source 2
target  3
label ""
]
edge [
source 3
target  4
label ""
]
edge [
source 4
target  5
label ""
]
edge [
source 5
target  6
label ""
]
edge [
source 6
target  7
label ""
]
edge [
source 7
target  8
label ""
]
edge [
source 8
target  9
label ""
]
edge [
source 8
target  10
label ""
]
edge [
source 10
target  11
label ""
]
edge [
source 11
target  19
label ""
]
edge [
source 19
target  20
label ""
]
edge [
source 20
target  65
label ""
]
edge [
source 65
target  66
label ""
]
edge [
source 66
target  67
label ""
]
edge [
source 67
target  68
label ""
]
edge [
source 68
target  69
label ""
]
edge [
source 69
target  70
label ""
]
edge [
source 70
target  71
label ""
]
edge [
source 70
target  72
label ""
]
edge [
source 72
target  73
label ""
]
edge [
source 73
target  74
label ""
]
edge [
source 73
target  87
label ""
]
edge [
source 73
target  103
label ""
]
edge [
source 73
target  113
label ""
]
edge [
source 113
target  114
label ""
]
edge [
source 113
target  119
label ""
]
edge [
source 114
target  115
label ""
]
edge [
source 114
target  116
label ""
]
edge [
source 114
target  120
label ""
]
edge [
source 120
target  121
label ""
]
edge [
source 115
target  117
label ""
]
edge [
source 117
target  118
label ""
]
edge [
source 118
target  123
label ""
]
edge [
source 103
target  104
label ""
]
edge [
source 103
target  106
label ""
]
edge [
source 103
target  108
label ""
]
edge [
source 108
target  122
label ""
]
edge [
source 106
target  107
label ""
]
edge [
source 107
target  109
label ""
]
edge [
source 104
target  105
label ""
]
edge [
source 104
target  110
label ""
]
edge [
source 110
target  111
label ""
]
edge [
source 87
target  88
label ""
]
edge [
source 87
target  89
label ""
]
edge [
source 87
target  102
label ""
]
edge [
source 102
target  112
label ""
]
edge [
source 112
target  124
label ""
]
edge [
source 124
target  125
label ""
]
edge [
source 125
target  126
label ""
]
edge [
source 89
target  90
label ""
]
edge [
source 90
target  91
label ""
]
edge [
source 91
target  92
label ""
]
edge [
source 92
target  93
label ""
]
edge [
source 93
target  94
label ""
]
edge [
source 94
target  95
label ""
]
edge [
source 95
target  96
label ""
]
edge [
source 96
target  97
label ""
]
edge [
source 96
target  100
label ""
]
edge [
source 88
target  98
label ""
]
edge [
source 98
target  99
label ""
]
edge [
source 99
target  101
label ""
]
edge [
source 74
target  75
label ""
]
edge [
source 75
target  76
label ""
]
edge [
source 76
target  77
label ""
]
edge [
source 77
target  78
label ""
]
edge [
source 78
target  79
label ""
]
edge [
source 79
target  80
label ""
]
edge [
source 80
target  81
label ""
]
edge [
source 80
target  85
label ""
]
edge [
source 71
target  82
label ""
]
edge [
source 71
target  86
label ""
]
edge [
source 86
target  149
label ""
]
edge [
source 149
target  150
label ""
]
edge [
source 150
target  151
label ""
]
edge [
source 151
target  152
label ""
]
edge [
source 82
target  83
label ""
]
edge [
source 83
target  84
label ""
]
edge [
source 9
target  12
label ""
]
edge [
source 12
target  13
label ""
]
edge [
source 13
target  14
label ""
]
edge [
source 14
target  15
label ""
]
edge [
source 15
target  16
label ""
]
edge [
source 16
target  17
label ""
]
edge [
source 17
target  18
label ""
]
edge [
source 18
target  21
label ""
]
edge [
source 21
target  22
label ""
]
edge [
source 21
target  24
label ""
]
edge [
source 24
target  26
label ""
]
edge [
source 24
target  35
label ""
]
edge [
source 35
target  36
label ""
]
edge [
source 36
target  37
label ""
]
edge [
source 37
target  38
label ""
]
edge [
source 38
target  39
label ""
]
edge [
source 39
target  40
label ""
]
edge [
source 40
target  41
label ""
]
edge [
source 41
target  42
label ""
]
edge [
source 42
target  43
label ""
]
edge [
source 43
target  44
label ""
]
edge [
source 43
target  47
label ""
]
edge [
source 43
target  50
label ""
]
edge [
source 43
target  52
label ""
]
edge [
source 50
target  51
label ""
]
edge [
source 47
target  48
label ""
]
edge [
source 44
target  45
label ""
]
edge [
source 45
target  46
label ""
]
edge [
source 26
target  27
label ""
]
edge [
source 27
target  49
label ""
]
edge [
source 49
target  53
label ""
]
edge [
source 53
target  54
label ""
]
edge [
source 54
target  55
label ""
]
edge [
source 55
target  56
label ""
]
edge [
source 56
target  57
label ""
]
edge [
source 57
target  58
label ""
]
edge [
source 57
target  60
label ""
]
edge [
source 57
target  61
label ""
]
edge [
source 58
target  59
label ""
]
edge [
source 22
target  23
label ""
]
edge [
source 22
target  127
label ""
]
edge [
source 127
target  128
label ""
]
edge [
source 127
target  130
label ""
]
edge [
source 130
target  131
label ""
]
edge [
source 131
target  132
label ""
]
edge [
source 132
target  133
label ""
]
edge [
source 133
target  134
label ""
]
edge [
source 133
target  135
label ""
]
edge [
source 135
target  136
label ""
]
edge [
source 135
target  140
label ""
]
edge [
source 135
target  145
label ""
]
edge [
source 145
target  146
label ""
]
edge [
source 140
target  141
label ""
]
edge [
source 141
target  142
label ""
]
edge [
source 141
target  143
label ""
]
edge [
source 134
target  137
label ""
]
edge [
source 137
target  138
label ""
]
edge [
source 138
target  139
label ""
]
edge [
source 138
target  144
label ""
]
edge [
source 138
target  153
label ""
]
edge [
source 128
target  129
label ""
]
edge [
source 129
target  147
label ""
]
edge [
source 147
target  148
label ""
]
edge [
source 23
target  25
label ""
]
edge [
source 23
target  28
label ""
]
edge [
source 23
target  62
label ""
]
edge [
source 62
target  63
label ""
]
edge [
source 63
target  64
label ""
]
edge [
source 64
target  154
label ""
]
edge [
source 154
target  155
label ""
]
edge [
source 154
target  157
label ""
]
edge [
source 154
target  164
label ""
]
edge [
source 157
target  158
label ""
]
edge [
source 158
target  159
label ""
]
edge [
source 159
target  160
label ""
]
edge [
source 159
target  161
label ""
]
edge [
source 161
target  162
label ""
]
edge [
source 162
target  163
label ""
]
edge [
source 155
target  156
label ""
]
edge [
source 28
target  29
label ""
]
edge [
source 29
target  30
label ""
]
edge [
source 25
target  31
label ""
]
edge [
source 31
target  32
label ""
]
edge [
source 32
target  33
label ""
]
edge [
source 33
target  34
label ""
]

]
